name: Build
on:
  push:
    - '!master'
jobs:
  publish:
    name: Building AWS Network Module
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      
      - name: Installing dependencies
        run: npm install -i

      - name: Building the package
        run: npm run build