name: Publish
on:
  push:

jobs:
  publish:
    name: Publish IaC Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Installing dependencies
        run: npm ci

      - name: Build the packge 
        run: npm run build

      - name: Publishing the new package to the registry 
        run: |
          npm publish
      - env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}