name: Publish
on:
  push:

jobs:
  publish:
    name: Publish IaC Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      
      - name: Authenticating with the registry
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Installing dependencies
        run: npm install -i

      - name: Building the package
        run: npm run build

      - name: Publishing the new package to the registry 
        run: npm publish